source 'https://rubygems.org'

gem 'byebug'
gem 'capybara'
gem 'capybara-selenium'
gem 'capybara_minitest_spec'
gem 'cucumber'
gem 'm'
gem 'minitest-rails'
gem 'minitest-rails-capybara'
gem 'minitest-reporters'
gem 'rails', '<6.0.0'
gem 'rspec'
gem 'rubocop', require: false
gem 'webdrivers'
