.PHONY: image install release 

include bin/dkr-config

export AWS_PROFILE = lr

image:
	@docker build -t ${TEST_CONTAINER_NAME}:${TEST_CONTAINER_VERSION} .

release:
	@docker tag ${TEST_CONTAINER_NAME}:${TEST_CONTAINER_VERSION} ${REGISTRY}/${TEST_CONTAINER_NAME}:${TEST_CONTAINER_VERSION}
	@docker push ${REGISTRY}/${TEST_CONTAINER_NAME}:${TEST_CONTAINER_VERSION}

install:
	@docker pull ${REGISTRY}/${TEST_CONTAINER_NAME}:${TEST_CONTAINER_VERSION}
	@docker tag ${TEST_CONTAINER_REGISTRY}/${TEST_CONTAINER_NAME}:${TEST_CONTAINER_VERSION} ${TEST_CONTAINER_NAME}:${TEST_CONTAINER_VERSION}
